# -*- coding: utf-8 -*-
"""2018CLfinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krewwKAmLeRSEqU8yqzyJBYUT6BtnJa-
"""

#Champions League Final RealMadrid vs Liverpool

#showed all passes by each player
!pip install mplsoccer
import numpy as np
import matplotlib.pyplot as plt
from mplsoccer import Pitch, Sbopen

parser = Sbopen()
df, related, freeze, tactics = parser.event(18245)

#--------------------------------------------------
#collected Real Madrid's pass data
mask_real_madrid = (df['type_name'] == 'Pass') & (df['team_name'] == 'Real Madrid') & (df['sub_type_name'] != 'Throw-in')
df_RMA_passes = df.loc[mask_real_madrid, ['x', 'y', 'end_x', 'end_y', 'player_name']]
RMA_names = df_RMA_passes['player_name'].unique()

#drowed pitch shape
pitch = Pitch(line_color ='black', pad_top =20)
fig, axs = pitch.grid(ncols = 4, nrows = 4, grid_height = 0.85, title_height = 0.06, axis = False, endnote_height = 0.04, title_space = 0.04, endnote_space = 0.01)

for name, ax in zip(RMA_names, axs['pitch'].flat[:len(RMA_names)]):
    ax.text(60, -10, name, ha ='center', va ='center', fontsize =9)
    player_df = df_RMA_passes.loc[df_RMA_passes['player_name'] == name]
    pitch.scatter(player_df.x, player_df.y, alpha = 0.2, color ='blue', ax = ax)
    pitch.arrows(player_df.x, player_df.y, player_df.end_x, player_df.end_y, color ='blue', ax = ax, width = 1)

for ax in axs['pitch'][-1, 16 - len(RMA_names):]:
    ax.remove()

#---------------------------------------------------

#collected Liverpool's pass data
mask_liverpool = (df['type_name'] == 'Pass') & (df['team_name'] == 'Liverpool') & (df['sub_type_name'] != 'Throw-in')
df_LIV_passes = df.loc[mask_liverpool, ['x', 'y', 'end_x', 'end_y', 'player_name']]
LIV_names = df_LIV_passes['player_name'].unique()

pitch = Pitch(line_color ='black', pad_top =20)
fig, axs = pitch.grid(ncols = 4, nrows = 4, grid_height = 0.85, title_height = 0.06, axis = False, endnote_height = 0.04, title_space = 0.04, endnote_space = 0.01)

for name, ax in zip(LIV_names, axs['pitch'].flat[:len(LIV_names)]):
    ax.text(60, -10, name, ha ='center', va ='center', fontsize =9)
    player_df = df_LIV_passes.loc[df_LIV_passes['player_name'] == name]
    pitch.scatter(player_df.x, player_df.y, alpha = 0.2, color ='blue', ax = ax)
    pitch.arrows(player_df.x, player_df.y, player_df.end_x, player_df.end_y, color ='blue', ax = ax, width = 1)

for ax in axs['pitch'][-1, 16 - len(LIV_names):]:
    ax.remove()

#-------------------------------------------------

#showed both team's shots map
pitch = Pitch(line_color ='black')
fig, ax = pitch.grid(grid_height = 0.9, title_height = 0.06, axis =False, endnote_height = 0.04, title_space = 0, endnote_space = 0)

#Real Madrid's shots
mask_realmadrid = (df.type_name == 'Shot') & (df.team_name =='Real Madrid')
df_RMA_shots = df.loc[mask_realmadrid, ['x', 'y', 'outcome_name', 'player_name']]

for i, row in df_RMA_shots.iterrows():
    if row['outcome_name'] == 'Goal':
        pitch.scatter(row.x, row.y, alpha = 1, s = 500, color ='blue', ax = ax['pitch'])
        pitch.annotate(row['player_name'], (row.x + 1, row.y - 2), ax = ax['pitch'], fontsize = 12)
    else:
        pitch.scatter(row.x, row.y, alpha = 0.2, s = 500, color ='blue', ax = ax['pitch'])

#Liverpool's shots
mask_shots_liverpool = (df.type_name == 'Shot') & (df.team_name == 'Liverpool')
df.LIV_shots = df.loc[mask_shots_liverpool, ['x', 'y', 'outcome_name', 'player_name']]

for i, row in df.LIV_shots.iterrows():
    if row['outcome_name'] == 'Goal':
        pitch.scatter(120 - row.x, 80 - row.y, alpha = 1, s = 500, color ='red', ax = ax['pitch'])
        pitch.annotate(row['player_name'], (120 - row.x + 1,80 - row.y - 2), ax= ax['pitch'], fontsize = 12)
    else:
        pitch.scatter(120 - row.x, 80 - row.y, alpha = 0.2, s = 500, color = 'red', ax = ax['pitch'])

fig.suptitle('Real Madrid (blue) and Liverpool (red) shots', fontsize = 30)
plt.show()

#-------------------------------------------------
pitch = Pitch(line_color ='black')
fig, ax = pitch.grid(grid_height = 0.9, title_height = 0.06, axis =False, endnote_height =0.04, title_space =0, endnote_space =0)

mask_bale = (df.type_name == 'Shot') & (df.player_name =='Gareth Frank Bale')
df_bale_shots = df.loc[mask_bale, ['x', 'y', 'outcome_name', 'player_name']]

for i, row in df_bale_shots.iterrows():
    if row['outcome_name'] == 'Goal':
        pitch.scatter(row.x,row.y, alpha = 1, s = 500, color ='blue', ax = ax['pitch'])
        pitch.annotate(row['player_name'], (row.x + 1, row.y - 2),ax = ax['pitch'], fontsize = 12)
    else:
        pitch.scatter(row.x, row.y, alpha = 0.2, s = 500, color ='blue', ax = ax['pitch'])

!pip install mplsoccer
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mplsoccer import Pitch, Sbopen

parser = Sbopen()
df, related, freeze, tactics = parser.event(18245)

#sub player information
subs = df.loc[df['type_name'] == 'Substitution', ['minute', 'team_name', 'player_name']]
print(subs)
#Salah left the pitch at the 29th minute

#pass data before and after
mask_liverpool = (df['type_name'] == 'Pass') & (df['team_name'] == 'Liverpool')
df_liverpool_pass = df.loc[mask_liverpool, ['x', 'y', 'end_x', 'end_y', 'minute', 'player_name', 'pass_recipient_name']]

salah_minute = 29

before = df_liverpool_pass[df_liverpool_pass['minute'] <= salah_minute]
after = df_liverpool_pass[df_liverpool_pass['minute'] > salah_minute]

pitch = Pitch(line_color ='black')
fig, axs = pitch.grid(ncols=2, grid_height =0.9, title_height= 0.06, axis = False, endnote_height = 0.04, title_space = 0, endnote_space = 0)

bin_statistic1 = pitch.bin_statistic(before.x, before.y, bins = (16, 12), normalize = False)
pcm1 = pitch.heatmap(bin_statistic1, cmap = 'Reds', edgecolor ='grey', ax = axs['pitch'][0])
axs['pitch'][0].set_title('Before Salah Substitution', fontsize = 16)

bin_statistic2 = pitch.bin_statistic(after.x, after.y, bins =(16, 12), normalize = False)
pcm2 = pitch.heatmap(bin_statistic2, cmap ='Reds', edgecolor ='grey', ax = axs['pitch'][1])
axs['pitch'][1].set_title('After Salah Substitution', fontsize = 16)
plt.show()

#------------------------------------------------------
#Real Madrid's pass heatmap
#Bale go onto the pitch at the 60th minute

mask_realmadrid = (df['type_name'] == 'Pass') & (df['team_name'] == 'Real Madrid')
df_realmadrid_pass = df.loc[mask_realmadrid, ['x', 'y', 'end_x', 'end_y', 'minute']]

bale_minute = 60

before2 = df_realmadrid_pass[df_realmadrid_pass['minute'] <= bale_minute]
after2 = df_realmadrid_pass[df_realmadrid_pass['minute'] > bale_minute]

pitch = Pitch(line_color ='black')
fig, axs = pitch.grid(ncols = 2, grid_height = 0.9, title_height = 0.06, axis = False, endnote_height = 0.04, title_space = 0, endnote_space = 0)

bin_statistic3 = pitch.bin_statistic(before2.x, before2.y, bins =(16, 12), normalize = False)
pcm3 = pitch.heatmap(bin_statistic3, cmap ='Reds', edgecolor ='grey', ax = axs['pitch'][0])
axs['pitch'][0].set_title('Before Bale Substitution', fontsize = 16)

bin_statistic4 = pitch.bin_statistic(after2.x, after2.y, bins =(16, 12), normalize = False)
pcm4 = pitch.heatmap(bin_statistic4, cmap ='Reds', edgecolor ='grey', ax = axs['pitch'][1])
axs['pitch'][1].set_title('After Bale Substitution', fontsize = 16)
plt.show()